# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3'

#Define services
services:

  #MySQL Database for the application
  backend-db:
    image: "mysql"
    container_name: AI_Backend_DB
    #Volume mounted for database for the storage
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306 # Forward the exposed port 3306 on the container to port 3306 on the host machine

    #Environment variable for DB name, user and password
    environment:
      - MYSQL_ROOT_PASSWORD=scrum

  #Back-end Spring Boot Application
  backend-app:
    #The docker file in scrum-app build the jar and provides the docker image with the following name.
#    build: ./scrum-app
    container_name: backend-app

    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    links:
      - backend-db

  #Fron-end Angular Application
  frontend-app:
#    build: ./scrum-ui
    container_name: frontend-app
    ports:
      - 4200:80
    links:
      - backend-app

#Volumes for DB data
volumes:
  db-data:
